services:
  LIM:
    image: LIM/rocm6.1
    container_name: LIM_docker
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - "video"
    ipc: "host"
    network_mode: 'host'
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp=unconfined"
    shm_size: "8G"
    volumes:
      - "$HOME/dockerx:/dockerx"
      - "..:/dockerx/LIM"
      - "/tmp/.X11-unix:/tmp/.X11-unix"  # Share the X11 socket with the container
      - type: bind
        source: /home/fmolina/code/Personal/LIM/src/LIM/data/raw
        target: /dockerx/LIM/data/
    working_dir: "/dockerx/LIM"
    entrypoint: "/bin/bash"
    stdin_open: true
    tty: true  # This is the equivalent of `-it` to keep the container interactive
    environment:
      - DISPLAY
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
    # ports:
      # - "43800:80"