services:
  IAE:
    image: IAE/cuda10.1-cudnn7
    container_name: IAE_docker
    runtime: nvidia  # Use the NVIDIA runtime
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]

    ipc: "host"
    network_mode: 'host'
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp=unconfined"
    shm_size: "8G"
    volumes:
      - "../src/submodules/IAE:/dockerx/IAE"
      - "/tmp/.X11-unix:/tmp/.X11-unix"  # Share the X11 socket with the container
      - type: bind
        source: /home/fmolina/code/Tesis/src/LIM/data
        target: /dockerx/IAE/data/
    working_dir: "/dockerx/IAE"
    entrypoint: "/bin/bash"
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - HSA_OVERRIDE_GFX_VERSION=10.3.0