MODEL:
  ENCODER:
    KNN: 20
    EMB_DIM: 1024
    PADDING: 0.1
    GRID_RES: 32
  LATENT_DIM: 256
  DECODER:
    HIDDEN_SIZE: 32
    N_BLOCKS: 5
    PADDING: 0.1


TRAINER:
    BATCH_SIZE: 1
    LEARNING_RATE: 1e-4
    EPOCHS: 1000
    ACCUM_STEPS: 1
    VALIDATION_PERIOD: 100
    BACKUP_PERIOD: 100
    VALIDATION_SPLIT: 0.2
    MULTIPROCESSING: false

DEVICE: "cuda"