MODEL:
  ENCODER:
    KNN: 20
    EMB_DIM: 1024
    PADDING: 0.1
    GRID_RES: 32
  LATENT_DIM: 256
  DECODER:
    HIDDEN_SIZE: 32
    N_BLOCKS: 5
    PADDING: 0.1

DEVICE: "cuda"

TRAINER:
    BATCH_SIZE: 1
    LEARNING_RATE: 1e-4
    EPOCHS: 1000
    ACCUM_STEPS: 1
    VALIDATION_PERIOD: 100
    BACKUP_PERIOD: 100
    VALIDATION_SPLIT: 0.2
    MULTIPROCESSING: false

    POINTCLOUD_TF:
      TRAIN:
        # CENTERZRANDOM:
        #   BASE_RATIO: 0.5
        DOWNSAMPLE:
          N_POINTS: 30000
        NOISE:
          NOISE: 0.005

      VALIDATION:
        # CENTERZRANDOM:
        #   BASE_RATIO: 0.5
        DOWNSAMPLE:
          N_POINTS: 30000
        NOISE:
          NOISE: 0.005

    IMPLICIT_GRID_TF:
      TRAIN:
        BREAKSYMMETRY:
          STD_DEV: 0.0004
        DOWNSAMPLE:
          N_POINTS: 2048

      VALIDATION:
        BREAKSYMMETRY:
          STD_DEV: 0.0004
