MODEL:
  PADDING: 0.1
  ENCODER:
    N_HIDDEN_LAYERS: 2
    GRID_RES: 32
  LATENT_DIM: 256
  DECODER:
    HIDDEN_SIZE: 32
    N_BLOCKS: 5

DEVICE: "cuda"

TRAINER:
    BATCH_SIZE: 1
    LEARNING_RATE: 
      VALUE: 1e-4
    EPOCHS: 1000
    ACCUM_STEPS: 1
    VALIDATION_PERIOD: 1
    BACKUP_PERIOD: 100
    VALIDATION_SPLIT: 0.2
    MULTIPROCESSING: false

    POINTCLOUD_TF:
      TRAIN:
        CENTERZRANDOM:
          BASE_RATIO: 0.5
        DOWNSAMPLE:
          N_POINTS: 4096
        NOISE:
          NOISE: 0.005

      VAL:
        # CENTERZRANDOM:
        #   BASE_RATIO: 0.5
        DOWNSAMPLE:
          N_POINTS: 4096
        # NOISE:
        #   NOISE: 0.005

    IMPLICIT_GRID_TF:
      TRAIN:
        BREAKSYMMETRY:
          STD_DEV: 0.0004
        DOWNSAMPLE:
          N_POINTS: 2048

      VAL:
        # BREAKSYMMETRY:
        #   STD_DEV: 0.0004
        DOWNSAMPLE:
          N_POINTS: 2048

TESTER:
  BATCH_SIZE: 1
  DOWNSAMPLE_SIZE: 1000
  RANSAC:
    MAX_ITERATIONS: 50000
    MAX_VALIDATION_STEPS: 1000
    SIMILARITY_THRESHOLD: 0.9
    DISTANCE_THRESHOLD: 0.05