MODEL:
  ENCODER:
    N_HIDDEN_LAYERS: 2
    KNN: 20
    EMB_DIM: 1024
    PADDING: 0.1
    GRID_RES: 32
  LATENT_DIM: 256
  DECODER:
    HIDDEN_SIZE: 32
    N_BLOCKS: 5
    PADDING: 0.1

DEVICE: "cuda"

TRAINER:
    BATCH_SIZE: 1
    LEARNING_RATE: 5e-3
    WEIGHT_DECAY: 1e-6
    MOMENTUM: 0.98
    EPOCHS: 40
    ACCUM_STEPS: 1
    VALIDATION_PERIOD: 1
    BACKUP_PERIOD: 100
    VALIDATION_SPLIT: 0.2
    MULTIPROCESSING: false

    POINTCLOUD_TF:
      TRAIN:
        # CENTERZRANDOM:
        #   BASE_RATIO: 0.5
        # DOWNSAMPLE:
        #   N_POINTS: 30000
        # NOISE:
        #   NOISE: 0.005

      VALIDATION:
        # CENTERZRANDOM:
        #   BASE_RATIO: 0.5
        # DOWNSAMPLE:
        #   N_POINTS: 30000
        # NOISE:
        #   NOISE: 0.005

TESTER:
  BATCH_SIZE: 1
  DOWNSAMPLE_SIZE: 1000
  RANSAC:
    MAX_ITERATIONS: 50000
    MAX_VALIDATION_STEPS: 1000
    SIMILARITY_THRESHOLD: 0.9
    DISTANCE_THRESHOLD: 0.05