#!/bin/bash
docker run -it --gpus all \
  --user root --ipc=host \
  --network=host \
  --cap-add=SYS_PTRACE \
  --security-opt=seccomp=unconfined \
  --shm-size=8g \
  -e DISPLAY=$DISPLAY \
  -v /etc/passwd:/etc/passwd:ro \
  -v /etc/group:/etc/group:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
  -v "$HOME/.Xauthority:/home/appuser/.Xauthority:rw" \
  -e XAUTHORITY=/home/appuser/.Xauthority \
  -e NVIDIA_VISIBLE_DEVICES=all \
  -e NVIDIA_DRIVER_CAPABILITIES=all \
  -v ./src/LIM/data/:/home/appuser/LIM/src/LIM/data \
  -v ./.aim/:/home/appuser/LIM/.aim \
  -v ./src/clean_scannet.py:/home/appuser/LIM/src/clean_scannet.py \
  -v ./src/LIM/models/layers/kpconv.py:/home/appuser/LIM/src/LIM/models/layers/kpconv.py \
  -v ./src/LIM/models/IAE/trainer.py:/home/appuser/LIM/src/LIM/models/IAE/trainer.py \
  -v ./src/LIM/models/PREDATOR/trainer.py:/home/appuser/LIM/src/LIM/models/PREDATOR/trainer.py \
  -v ./src/LIM/models/PREDATOR/predator.py:/home/appuser/LIM/src/LIM/models/PREDATOR/predator.py \
  -v ./src/LIM/models/PREDATOR/encoder.py:/home/appuser/LIM/src/LIM/models/PREDATOR/encoder.py \
  -v ./src/LIM/models/PREDATOR/decoder.py:/home/appuser/LIM/src/LIM/models/PREDATOR/decoder.py \
  -v ./src/LIM/models/modelI.py:/home/appuser/LIM/src/LIM/models/modelI.py \
  -v ./src/main.py:/home/appuser/LIM/src/main.py \
  -v ./src/config/:/home/appuser/LIM/src/config/ \
  -v ./src/LIM/training/trainer.py:/home/appuser/LIM/src/LIM/training/trainer.py \
  -v ./src/LIM/training/backups/:/home/appuser/LIM/src/LIM/training/backups \
  -v ./src/LIM/data/structures/bunny.py:/home/appuser/LIM/src/LIM/data/structures/bunny.py \
  -v ./src/LIM/data/structures/pcloud.py:/home/appuser/LIM/src/LIM/data/structures/pcloud.py \
  -v ./src/LIM/data/sets/registration_bunny.py:/home/appuser/LIM/src/LIM/data/sets/registration_bunny.py \
  -v ./src/LIM/log/console.py:/home/appuser/LIM/src/LIM/log/console.py \
  -v ./src/LIM/log/__init__.py:/home/appuser/LIM/src/LIM/log/__init__.py \
  -v ./src/LIM/models/layers/batchnorm.py:/home/appuser/LIM/src/LIM/models/layers/batchnorm.py \
  -v ./src/LIM/models/layers/conv1d.py:/home/appuser/LIM/src/LIM/models/layers/conv1d.py \
  -v ./src/LIM/metrics/losses.py:/home/appuser/LIM/src/LIM/metrics/losses.py \
  -v ./src/LIM/models/evaluator.py:/home/appuser/LIM/src/LIM/models/evaluator.py \
  -v ./src/LIM/metrics/metrics.py:/home/appuser/LIM/src/LIM/metrics/metrics.py \
  -v ./src/test_bunny.py:/home/appuser/LIM/src/test_bunny.py \
  lim/cuda12.4-cudnn9:leftraru
