method: shapenet_dfnet
data:
  input_type: partial_pointcloud
  classes: null
  path: data/ShapeNet
  pointcloud_n: 2048
  pointcloud_noise: 0.005
  points_subsample: 2048
  points_file: points.npz
  points_iou_file: points.npz
  pointcloud_file: pointcloud.npz
  voxels_file: null
  part_ratio: 0.5
  partial_type: centery_random
  rotate: true
model:
  encoder: dgcnn_cls
  encoder_kwargs:
    feat_dim: 1024
    plane_type: ['xz', 'xy', 'yz']
    plane_resolution: 64
    unet: True
    unet_kwargs:
      depth: 4
      merge_mode: concat
      start_filts: 32
  decoder: simple_local
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
  c_dim: 32
training:
  out_dir: out/shapenet/dgcnn
  batch_size: 16
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 100
  visualize_every: 50000
  validate_every: 10000
  checkpoint_every: 2000
  backup_every: 10000
  n_workers: 8
  n_workers_val: 4
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  remove_wall: true
  model_file: model_best.pt
